--Tabla roles
insert into roles (role) values ('Estimator');
insert into roles (role) values ('Electrician');
insert into roles (role) values ('Subcontractor');
insert into roles (role) values ('Supervisor');
insert into roles (role) values ('Project Manager');
insert into roles (role) values ('Electrician');
insert into roles (role) values ('Estimator');
insert into roles (role) values ('Electrician');
insert into roles (role) values ('Engineer');
insert into roles (role) values ('Construction Expeditor');
insert into roles (role) values ('Construction Worker');
insert into roles (role) values ('Engineer');
insert into roles (role) values ('Construction Foreman');
insert into roles (role) values ('Surveyor');
insert into roles (role) values ('Estimator');
insert into roles (role) values ('Construction Foreman');
insert into roles (role) values ('Construction Manager');
insert into roles (role) values ('Project Manager');
insert into roles (role) values ('Engineer');
insert into roles (role) values ('Architect');
insert into roles (role) values ('Project Manager');
insert into roles (role) values ('Surveyor');
insert into roles (role) values ('Supervisor');
insert into roles (role) values ('Estimator');
insert into roles (role) values ('Subcontractor');
insert into roles (role) values ('Electrician');
insert into roles (role) values ('Subcontractor');
insert into roles (role) values ('Estimator');
insert into roles (role) values ('Estimator');
insert into roles (role) values ('Construction Worker');
insert into roles (role) values ('Construction Foreman');
insert into roles (role) values ('Construction Manager');
insert into roles (role) values ('Construction Expeditor');
insert into roles (role) values ('Project Manager');
insert into roles (role) values ('Project Manager');
insert into roles (role) values ('Construction Foreman');
insert into roles (role) values ('Supervisor');
insert into roles (role) values ('Construction Foreman');
insert into roles (role) values ('Estimator');
insert into roles (role) values ('Project Manager');
insert into roles (role) values ('Construction Foreman');
insert into roles (role) values ('Project Manager');
insert into roles (role) values ('Engineer');
insert into roles (role) values ('Supervisor');
insert into roles (role) values ('Construction Expeditor');
insert into roles (role) values ('Project Manager');
insert into roles (role) values ('Electrician');
insert into roles (role) values ('Construction Foreman');
insert into roles (role) values ('Estimator');
insert into roles (role) values ('Subcontractor');
insert into roles (role) values ('Subcontractor');
insert into roles (role) values ('Electrician');
insert into roles (role) values ('Supervisor');
insert into roles (role) values ('Electrician');
insert into roles (role) values ('Engineer');
insert into roles (role) values ('Architect');
insert into roles (role) values ('Construction Worker');
insert into roles (role) values ('Architect');
insert into roles (role) values ('Construction Manager');
insert into roles (role) values ('Construction Foreman');
insert into roles (role) values ('Subcontractor');
insert into roles (role) values ('Architect');
insert into roles (role) values ('Construction Foreman');
insert into roles (role) values ('Surveyor');
insert into roles (role) values ('Construction Manager');
insert into roles (role) values ('Supervisor');
insert into roles (role) values ('Supervisor');
insert into roles (role) values ('Construction Expeditor');
insert into roles (role) values ('Electrician');
insert into roles (role) values ('Architect');
insert into roles (role) values ('Estimator');
insert into roles (role) values ('Supervisor');
insert into roles (role) values ('Supervisor');
insert into roles (role) values ('Estimator');
insert into roles (role) values ('Electrician');
insert into roles (role) values ('Surveyor');
insert into roles (role) values ('Electrician');
insert into roles (role) values ('Architect');
insert into roles (role) values ('Architect');
insert into roles (role) values ('Construction Manager');
insert into roles (role) values ('Electrician');
insert into roles (role) values ('Architect');
insert into roles (role) values ('Construction Expeditor');
insert into roles (role) values ('Subcontractor');
insert into roles (role) values ('Construction Manager');
insert into roles (role) values ('Supervisor');
insert into roles (role) values ('Surveyor');
insert into roles (role) values ('Engineer');
insert into roles (role) values ('Engineer');
insert into roles (role) values ('Construction Worker');
insert into roles (role) values ('Construction Expeditor');
insert into roles (role) values ('Electrician');
insert into roles (role) values ('Architect');
insert into roles (role) values ('Surveyor');
insert into roles (role) values ('Electrician');
insert into roles (role) values ('Construction Foreman');
insert into roles (role) values ('Electrician');
insert into roles (role) values ('Supervisor');
insert into roles (role) values ('Project Manager');
insert into roles (role) values ('Construction Worker');